### ISSUE TITLE
Amphetamine forgets its settings when quit

### ISSUE THREAD

**Issue by Evertt** [x74353/AmphetamineHelper#1]
This only happens on some of my Macs and not all of them. When I quit Amphetamine and then restart it again, it starts as if it's the first time. Showing the introduction window, even though I tell it every time not to show me again, and showing the dock icon, even though I tell it every time to hide it.

Do you have any idea what might be causing this and what I can do about it?

**Comment by x74353** [comment]
Hi @Evertt - this is not the support forum for Amphetamine. Please visit https://amphetamine.freshdesk.com/support/home
